### ISSUE TITLE
appending time to all dates

### ISSUE THREAD

**Issue by kfherbert** [harvard-library/aspace-import-excel#15]
When we upload a spreadsheet using the plug in the resulting records have the a time stamp added to the date: 1985-01-01T00:00:00+00:00. This is happening with all the records and for both start and end dates.  We are running ArchivesSpace  v2.0.0 and v1.0 of the plugin.

**Comment by bobbi-SMR** [comment]
Hi,
Another user had this problem (see the now-closed issue https://github.com/harvard-library/aspace-import-excel/issues/9 ); it seems to have to do with differing versions of Excel; the solution was to set the format of date columns to “text” rather than “general”.  I thought I’d done that in the template I provide; perhaps the setting didn’t extend down enough rows?
 
If that’s the case, I think you just need to select those columns, and use the “format cell” to set them all to “text”.
