### ISSUE TITLE
The file you have chosen is not an Excel Spreadsheet

### ISSUE THREAD

**Issue by wjlevay** [harvard-library/aspace-import-excel#41]
I'm testing this out on a local instance of ASpace (2.4.1 on Windows 10, using the embedded database), but cannot get past this error. This occurs with every xslx and xls I've thrown at it, and even when using an unedited copy of the provided Excel template.

**Comment by bobbi-SMR** [comment]
Hi,

I’m happy to work with you to trouble-shoot this, but I am not in a position to replicate your environment.
Perhaps the answers to my questions below will help me trouble-shoot:

When you get the unedited copy of the Excel template, are you downloading it from GitHub?

If so, are you just downloading it, or first opening it up in Excel (I’m assuming your browser/Windows 10 interaction gives you the option of Open with or Save File).
   -- If you’re Opening With, then Saving: what version of Excel are you using?
     -- Are you then doing a “Save as…” (I believe you have to, since the template on GitHub is read-only), and, if so, what type do you select?

To get technical: you are getting this error because the javascript check  on the file object created by the Add File process is looking for a file object type whose value is application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

Cheers,
Bobbi

**Comment by wjlevay** [comment]
Thanks. I checked the mime-type of the spreadsheets I've been trying to import and indeed they are all application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

I'm thinking I must have something misconfigured in my environment. I'll keep troubleshooting.

**Comment by bobbi-SMR** [comment]
Hi, Bill,

It occurred to me that if you have Web Developer tools in your browser (I use FireFox), you could set breakpoints in assets/tree_extensions.js (around line 97 and/or 99), and see what you get as the fileObj.type.

Let me know if that’s helpful.

Cheers,
Bobbi
