### ISSUE TITLE
Compatibility with AS v2.7.0?

### ISSUE THREAD

**Issue by noahgh221** [harvard-library/aspace-import-excel#61]
Since upgrading ArchivesSpace to v2.7.0, I have noticed that when I trigger a spreadsheet import from a resource record, I receive a Bad Gateway error in the staff interface (after a considerable delay).

I also see the following "Calling a deprecated endpoint" error in my log file (logs/archivesspace.out):

![image](https://user-images.githubusercontent.com/7328518/69095628-b7f8f980-0a20-11ea-945d-968e8cc6b84a.png)

The plugin was working as expected in v2.6.0, so I'm wondering if something has changed in v2.7.0 that makes the current plugin incompatible (and if it's an easy fix:)). Thanks for considering.

**Comment by kschlottmann** [comment]
FWIW, I just tested a small import via the plugin on our 2.7.0 dev instance (we are hosted by Lyrasis), and it imported correctly.

**Comment by noahgh221** [comment]
Thanks @kschlottmann . Looking into this a bit more, I was able to get the import to work (there were some spreadsheet formatting issues..).  Even so, I do still get the "CALLING A DEPRECATED ENDPOINT" warning in my logs, but it doesn't seem like a critical error.

**Comment by pobocks** [comment]
I'll take a look and see which endpoint - I can't devote _work_ time to
fixing it right now, but either Bobbi or I can probably figure a
replacement for it before it gets actually removed.

**Comment by noahgh221** [comment]
thanks @pobocks . To add another wrinkle, Lyrasis was reporting that ASpace crashed every time we tried to import the malformed spreadsheet. That's why I started looking into this.  Seems weird that a malformed spreadsheet would crash ASpace entirely rather than just throw an error. In the meantime, I will try to be more vigilant in enforcing spreadsheet formatting standards (wish me luck).

**Comment by pobocks** [comment]
Oh, wow.  That's concerning - though I guess "unhandled exception" might
well do it.

**Comment by bobbi-SMR** [comment]
I suspect that the deprecated route is being invoked by the javascript that helps determine which leaf of the tree is used as the starting point for the ingest.

In terms of "crashing the system": I'd really like to see the related log file(s).

**Comment by noahgh221** [comment]
@bobbi-SMR , I forwarded you a message containing a snippet of the log file along with some other info. Thanks!

**Comment by bobbi-SMR** [comment]
Hi, Noah,

I ran into a problem with the excel file you sent that I can't explain:
  When trying to ingest the file, the code didn't get past the "read in and parse the excel file" piece, resulting in the following message in the log file:
`F, [2019-11-20T10:46:42.871000 #12100] FATAL -- : RuntimeError ({"error":"undefined method `getSQLState' for java.lang.OutOfMemoryError: Java heap space:Java::JavaLang::OutOfMemoryError\nDid you mean?  getClass"}
`
(This, btw, might have caused Aspace to crash).

I opened the file, wrote it out as a csv, read that csv back in, and tried again.  There were no problems.

I don't have any expertise in evaluating .xlsx files for problems, but I'm wondering if whatever the problem is is the root cause.
I did all this in 5.2, as I'm only now in the process of upgrading myself, but I doubt that the file as you sent it to me is going to get past the parsing step.

[thanks for your kind words wrt the plugin :-)]

**Comment by noahgh221** [comment]
Interesting, I will never understand Excel's mysteries...  Thanks for the additional info though. I was able to get this spreadsheet to load after reformatting it to meet the template specs. I'll close out this issue and chalk it up to...Excel being Excel.
